services:

  broker:
    image: rabbitmq:management-alpine
    restart: unless-stopped
    hostname: broker
    env_file: .env
    ports:
      - 5672:5672
      - 15672:15672 # ui

  tsdb:
    image: influxdb:2-alpine
    restart: unless-stopped
    hostname: tsdb
    env_file: .env
    ports:
      - 8086:8086

  frontend:
    image: grafana/grafana
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000
    volumes: 
      - ./grafana-provisioning:/etc/grafana/provisioning

  crawler:
    build: apps
    env_file: .env
    restart: no
    environment:
      - APP=crawler.py
      - LOG_LEVEL=DEBUG
    depends_on:
      - broker

  worker:
    build: apps
    env_file: .env
    restart: unless-stopped
    environment:
      - APP=worker.py
      - LOG_LEVEL=DEBUG
    depends_on:
      - broker
      - tsdb
    deploy:
      replicas: 3